import type { Metadata } from "next";
import { Nunito_Sans, Roboto_Mono } from "next/font/google";
import type { ReactNode } from "react";
import "../styles/main.scss";

const nunitoSans = Nunito_Sans({
	variable: "--font-nunito-sans",
	subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
	variable: "--font-roboto-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Bevi Docs",
	description: "Generated by create next app",
};

const RootLayout = ({
	children,
}: Readonly<{
	children: ReactNode;
}>) => {
	return (
		<html lang="pt-BR">
			<body
				className={`${nunitoSans.variable} ${robotoMono.variable} antialiased min-h-screen bg-gray-95`}
			>
				{children}
			</body>
		</html>
	);
};

export default RootLayout;
